"""
Language detection for URL segments: the scoring helper plus the CLDR-derived
language/territory code sets it checks (from babel 2.18, no longer a dependency).
"""

from functools import lru_cache


@lru_cache(maxsize=1024)
def langcodes_score(language: str, segment: str) -> int:
    "Score a URL segment as a language cue: +1 matching locale, -1 mismatching, 0 unrecognized."
    lang, _, territory = segment.replace("_", "-").partition("-")
    lang = lang.lower()
    if lang not in ISO_LANGS:
        return 0
    if territory and territory.upper() not in ISO_TERRS:
        return 0
    return 1 if lang == language else -1


# ISO 639-1 language codes accepted by CLDR (167 codes).
# Generated by: all ab where Locale.parse(ab) succeeds in babel 2.18.
ISO_LANGS = frozenset(
    """
    aa ab af ak am an ar as az ba be bg bh bm bn bo br bs ca ce co cs cu cv cy da de dv
    dz ee el en eo es et eu fa ff fi fo fr fy ga gd gl gn gu gv ha he hi hr ht hu hy ia
    id ie ig ii in io is it iu iw ja ji jv jw ka ki kk kl km kn ko ks ku kw ky la lb lg
    ln lo lt lu lv mg mi mk ml mn mo mr ms mt my nb nd ne nl nn no nr nv ny oc om or os
    pa pl ps pt qu rm rn ro ru rw sa sc sd se sg si sk sl sn so sq sr ss st su sv sw ta
    te tg th ti tk tl tn to tr ts tt tw ug uk ur uz ve vi vo wa wo xh yi yo za zh zu
    """.split()
)

# ISO 3166-1 territory codes recognized by CLDR (265 codes).
# Generated by: sorted 2-letter alpha codes in babel 2.18 Locale("en").territories,
# plus "UK" (common web alias for GB).
ISO_TERRS = frozenset(
    """
    AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM
    BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CP CQ CR CU CV CW
    CX CY CZ DE DG DJ DK DM DO DZ EA EC EE EG EH ER ES ET EU EZ FI FJ FK FM FO FR GA GB
    GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU IC ID IE IL IM
    IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS
    LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA
    NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA QO
    RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TA TC
    TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UK UM UN US UY UZ VA VC VE VG VI
    VN VU WF WS XA XB XK YE YT ZA ZM ZW ZZ
    """.split()
)
